package net.cf.form.engine.object;

import java.util.List;

/**
 * 对象的字段
 *
 * @author clouds
 */
public interface XField {

    /**
     * 获取字段的名称
     *
     * @return
     */
    String getName();

    /**
     * 获取字段的标题
     *
     * @return
     */
    String getTitle();

    /**
     * 获取字段的列名
     *
     * @return
     */
    String getColumnName();

    default boolean isPrimary() {
        return false;
    }

    /**
     * 是否自动生成的主键
     *
     * @return
     */
    default boolean isAutoGeneratedPrimary() {
        return false;
    }

    /**
     * 是否是集合
     *
     * @return
     */
    boolean isCollection();

    /**
     * 获取数据类型
     *
     * @return
     */
    DataType getDataType();

    /**
     * 获取数据的长度
     *
     * @return
     */
    int getDataLength();

    /**
     * 获取数据的精度
     *
     * @return
     */
    short getDataPrecision();

    /**
     * 获取默认值
     *
     * @return
     */
    Object getDefaultValue();

    /**
     * 获取字段的子属性
     *
     * @return
     */
    List<XFieldProperty> getSubFields();
}
