package net.cf.form.engine.object;

import java.util.List;

/**
 * 模型的字段
 *
 * @author clouds
 */
public interface XField<P extends XFieldProperty> {

    /**
     * 获取字段的名称
     *
     * @return
     */
    String getName();

    /**
     * 获取字段的编号
     *
     * @return
     */
    String getCode();

    /**
     * 获取字段的列名
     *
     * @return
     */
    String getColumnName();

    /**
     * 是否主键字段
     *
     * @return
     */
    default boolean isPrimary() {
        return false;
    }

    /**
     * 是否自动生成的主键字段
     *
     * @return
     */
    default boolean isAutoGeneratedPrimary() {
        return false;
    }

    /**
     * 是否是集合
     *
     * @return
     */
    boolean isCollection();

    /**
     * 获取数据类型
     *
     * @return
     */
    DataType getDataType();

    /**
     * 获取数据的长度
     *
     * @return
     */
    Integer getDataLength();

    /**
     * 获取数据的精度
     *
     * @return
     */
    Integer getDataPrecision();

    /**
     * 获取最小值
     *
     * @return
     */
    Number getMinValue();

    /**
     * 获取最大值
     *
     * @return
     */
    Number getMaxValue();

    /**
     * 获取字段的子属性
     *
     * @return
     */
    List<P> getProperties();

    /**
     * 获取默认值
     *
     * @return
     */
    Object getDefaultValue();

}
