package net.cf.form.engine.object;

import net.cf.commons.util.js.JsScriptUtils;
import net.cf.form.commons.DefaultValue;
import net.cf.form.commons.DefaultValueType;
import net.cf.form.commons.FieldDefinition;
import net.cf.form.engine.field.XFieldProperty;
import net.cf.form.engine.field.XField;
import net.cf.form.engine.repository.data.value.DataType;

import java.util.List;

public class XFieldTestImpl implements XField {

    private FieldDefinition fieldDef;

    public XFieldTestImpl(FieldDefinition fieldDef) {
        this.fieldDef = fieldDef;
    }

    @Override
    public boolean isDeamon() {
        return false;
    }

    @Override
    public String getName() {
        return fieldDef.getName();
    }

    @Override
    public String getTitle() {
        return fieldDef.getTitle();
    }

    @Override
    public String getColumnName() {
        return fieldDef.getName();
    }

    @Override
    public boolean isAutoGeneratedPrimary() {
        return false;
    }

    @Override
    public boolean isCollection() {
        return fieldDef.isCollection();
    }

    @Override
    public DataType getDataType() {
        return null;
    }

    @Override
    public int getDataLength() {
        return 0;
    }

    @Override
    public short getDataPrecision() {
        return 0;
    }

    @Override
    public Object getDefaultValue() {
        DefaultValue defaultValue = this.fieldDef.getDefaultValue();
        if (defaultValue == null) {
            return null;
        }

        DefaultValueType defaultValueType = defaultValue.getType();
        if (DefaultValueType.LITERAL == defaultValueType) {
            return defaultValue.getValue();
        } else if (DefaultValueType.FORMULA == defaultValueType) {
            return JsScriptUtils.eval(defaultValue.getValue());
        }

        return null;
    }

    @Override
    public List<XFieldProperty> getProperties() {
        return null;
    }
}
