package net.cf.form.engine.field;

import net.cf.form.engine.fieldtype.XFieldType;
import net.cf.form.engine.fieldtype.XFieldTypeAttribute;
import net.cf.form.engine.repository.data.value.DataType;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 对象中的字段实例（是XFieldType的实例）
 *
 * @author clouds
 */
@Deprecated
public class XFieldImpl implements XField {

    /**
     * 字段的类型
     */
    private XFieldType fieldType;

    private boolean isDeamon;


    /**
     * 类型（用于替换fieldType）
     */
    private String type;

    /**
     * 名称
     */
    private String name;

    /**
     * 标题
     */
    private String title;

    /**
     * 是否自动生成
     */
    private boolean autoGenerated;

    /**
     * 是否集合
     */
    private boolean isCollection;

    /**
     * 数据类型
     */
    private DataType dataType;

    /**
     * 数据长度
     */
    private int length;

    /**
     * 数据精度
     */
    private short precision;

    /**
     * 默认值
     */
    private Object defaultValue;

    /**
     * 字段的属性
     */
    @Deprecated
    private Map<String, Object> attributes;

    /**
     * 是否平台内置字段
     */
    @Deprecated
    private boolean builtin;

    /**
     * 是否持久化
     */
    @Deprecated
    private boolean persistence;

    /**
     * 列的名称（持久化时有效）
     */
    private String columnName;

    /**
     * 字段的数据类型
     */
    @Deprecated
    private net.cf.form.engine.repository.data.DataType dataTypeBak;

    /**
     * 字段的子属性
     */
    private List<XFieldProperty> properties;

    public XFieldImpl(XFieldType fieldType, String name) {
        this.fieldType = fieldType;
        this.name = name;
    }

    public XFieldImpl(String type, String name) {
        this.type = type;
        this.name = name;
    }

    @Override
    public boolean isDeamon() {
        return false;
    }

    public XFieldType getFieldType() {
        return fieldType;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Map<String, Object> getAttributes() {
        return attributes;
    }

    /**
     * 获取某个属性的名称
     *
     * @param name
     * @return
     */
    public Object getAttributeValue(String name) {
        Object value = attributes.get(name);
       if (value == null) {
           XFieldTypeAttribute fieldTypeAttribute = this.fieldType.getAttribute(name);
           if (fieldTypeAttribute != null && fieldTypeAttribute.getDefaultValue() != null) {
               return fieldTypeAttribute.getDefaultValue();
           }
       }

       return value;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }

    /**
     * 设置属性值
     *
     * @param name
     * @param value
     */
    public void setAttributeValue(String name, Object value) {
        if (this.attributes == null) {
            this.attributes = new HashMap<>();
        }

        this.attributes.put(name, value);
    }

    public boolean isBuiltin() {
        return builtin;
    }

    public void setBuiltin(boolean builtin) {
        this.builtin = builtin;
    }

    public boolean isPersistence() {
        return persistence;
    }

    public void setPersistence(boolean persistence) {
        this.persistence = persistence;
    }

    @Override
    public String getColumnName() {
        return columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    public net.cf.form.engine.repository.data.DataType getDataTypeBak() {
        return dataTypeBak;
    }

    public List<XFieldProperty> getProperties() {
        return properties;
    }

    public void setProperties(List<XFieldProperty> properties) {
        this.properties = properties;
    }

    @Override
    public boolean isAutoGeneratedPrimary() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    @Override
    public boolean isCollection() {
        return isCollection;
    }

    public void setCollection(boolean collection) {
        isCollection = collection;
    }

    @Override
    public DataType getDataType() {
        return dataType;
    }

    public void setDataType(DataType dataType) {
        this.dataType = dataType;
    }

    @Override
    public int getDataLength() {
        return length;
    }

    public void setLength(int length) {
        this.length = length;
    }

    @Override
    public short getDataPrecision() {
        return precision;
    }

    public void setPrecision(short precision) {
        this.precision = precision;
    }

    @Override
    public Object getDefaultValue() {
        return defaultValue;
    }

    public void setDefaultValue(Object defaultValue) {
        this.defaultValue = defaultValue;
    }
}
