-- 创建SCHEMA
CREATE SCHEMA OQL;

-- 创建出差表
CREATE TABLE OQL.TRV_TB
(
    `APPLY_ID`    INT          NOT NULL AUTO_INCREMENT,
    `ENT_KEY`    VARCHAR(32)  NOT NULL,
    `USER_ID`     VARCHAR(32)  NOT NULL,
    `START_DATE`  DATE         NOT NULL,
    `END_DATE`    DATE         NOT NULL,
    `REASON`      VARCHAR(200) NOT NULL DEFAULT '',
    `ATTACH`      TEXT,
    `STATUS`      VARCHAR(10) NOT NULL DEFAULT '',
    `CREATED_BY`  VARCHAR(20)  NOT NULL,
    `CREATED_AT`  DATETIME     NOT NULL,
    `MODIFIED_BY` VARCHAR(20) NULL,
    `MODIFIED_AT` DATETIME NULL,
    PRIMARY KEY (`APPLY_ID`)
);

-- 创建出差行程表
CREATE TABLE OQL.TRV_SCHE_TB
(
    `SCHE_ID`     INT          NOT NULL AUTO_INCREMENT,
    `APPLY_ID`    INT          NOT NULL,
    `START_DATE`  DATE         NOT NULL,
    `END_DATE`    DATE         NOT NULL,
    `DEST`        VARCHAR(100) NOT NULL DEFAULT '',
    `TODO`        VARCHAR(200) NOT NULL DEFAULT '',
    `STATUS`      VARCHAR(10) NOT NULL DEFAULT '',
    `ENTP_KEY`    VARCHAR(32)  NOT NULL,
    `CREATED_BY`  VARCHAR(20)  NOT NULL,
    `CREATED_AT`  DATETIME     NOT NULL,
    `MODIFIED_BY` VARCHAR(20) NULL,
    `MODIFIED_AT` DATETIME NULL,
    PRIMARY KEY (`SCHE_ID`)
);
