-- 创建出差表
CREATE TABLE TRAVEL
(
    `APPLY_ID`    VARCHAR(36)  NOT NULL,
    `APPLY_NAME`  VARCHAR(64)  NOT NULL,
    `START_DATE`  DATE         NULL,
    `END_DATE`    DATE         NULL,
    `REASON`      VARCHAR(200) NULL DEFAULT '',
    `ATTACH`      TEXT,
    `STATUS`      VARCHAR(10)  NULL DEFAULT '',
    `CREATOR_NAME` VARCHAR(32)  NULL,
    `CREATOR_KEY`  VARCHAR(20)  NULL,
    `CREATED_AT`  DATETIME     NULL,
    `MODIFIER_NAME` VARCHAR(32)  NULL,
    `MODIFIER_KEY` VARCHAR(20)  NULL,
    `MODIFIED_AT` DATETIME     NULL,
    `OWNER_KEY`   VARCHAR,
     REVISION     INT,
     `DELETED`    VARCHAR,
    PRIMARY KEY (`APPLY_ID`)
);

-- 创建员工表
CREATE TABLE STAFF
(
    `STA_ID`       INT NOT NULL AUTO_INCREMENT,
    `STA_CODE`     VARCHAR(20)  NOT NULL,
    `STA_NAME`     VARCHAR(32)  NOT NULL,
    `HOBBIES`      text  NULL,
    `CREATOR_NAME` VARCHAR(32)  NULL,
    `CREATOR_KEY`  VARCHAR(20)  NULL,
    `CREATED_AT`    DATETIME     NULL,
    `MODIFIER_NAME` VARCHAR(32)  NULL,
    `MODIFIER_KEY`  VARCHAR(20)  NULL,
    `MODIFIED_AT`   DATETIME     NULL,
    PRIMARY KEY (`STA_ID`)
);
-- 创建兴趣爱好表
CREATE TABLE HOBBY
(
    `CODE`         VARCHAR(10)  NOT NULL,
    `NAME`         VARCHAR(32)  NOT NULL,
    `DESCR`        VARCHAR(1024)  NULL,
    `CREATOR_NAME` VARCHAR(32)  NULL,
    `CREATOR_KEY`  VARCHAR(20)  NULL,
    `CREATED_AT`    DATETIME     NULL,
    `MODIFIER_NAME` VARCHAR(32)  NULL,
    `MODIFIER_KEY`  VARCHAR(20)  NULL,
    `MODIFIED_AT`   DATETIME     NULL,
    PRIMARY KEY (`CODE`)
);