-- 创建出差表
CREATE TABLE TRAVEL
(
    `APPLY_ID`    VARCHAR(36)  NOT NULL,
    `APPLY_NAME`  VARCHAR(64)  NOT NULL,
    `USER_ID`     VARCHAR(32)  NULL,
    `START_DATE`  DATE         NULL,
    `END_DATE`    DATE         NULL,
    `REASON`      VARCHAR(200) NULL DEFAULT '',
    `ATTACH`      TEXT,
    `STATUS`      VARCHAR(10)  NULL DEFAULT '',
    `CREATOR_NAME` VARCHAR(32)  NULL,
    `CREATOR_KEY`  VARCHAR(20)  NULL,
    `CREATED_AT`  DATETIME     NULL,
    `MODIFIER_NAME` VARCHAR(32)  NULL,
    `MODIFIER_KEY` VARCHAR(20)  NULL,
    `MODIFIED_AT` DATETIME     NULL,
    PRIMARY KEY (`APPLY_ID`)
);

-- 创建兴趣爱好表
CREATE TABLE HOBBY
(
    `RECORD_ID`    INT NOT NULL AUTO_INCREMENT,
    `NAME`         VARCHAR(32)  NOT NULL,
    `DESCR`        VARCHAR(1024)  NULL,
    `CREATOR_NAME` VARCHAR(32)  NULL,
    `CREATOR_KEY`  VARCHAR(20)  NULL,
    `CREATED_AT`    DATETIME     NULL,
    `MODIFIER_NAME` VARCHAR(32)  NULL,
    `MODIFIER_KEY`  VARCHAR(20)  NULL,
    `MODIFIED_AT`   DATETIME     NULL,
    PRIMARY KEY (`RECORD_ID`)
);