-- 创建出差表
CREATE TABLE Travel
(
    `APPLY_ID`    VARCHAR(36)  NOT NULL,
    `APPLY_NAME`  VARCHAR(64)  NOT NULL,
    `USER_ID`     VARCHAR(32)  NULL,
    `START_DATE`  DATE         NULL,
    `END_DATE`    DATE         NULL,
    `REASON`      VARCHAR(200) NULL DEFAULT '',
    `ATTACH`      TEXT,
    `STATUS`      VARCHAR(10)  NULL DEFAULT '',
    `CREATED_BY`  VARCHAR(20)  NULL,
    `CREATED_AT`  DATETIME     NULL,
    `MODIFIED_BY` VARCHAR(20)  NULL,
    `MODIFIED_AT` DATETIME     NULL,
    PRIMARY KEY (`APPLY_ID`)
);