DROP TABLE IF EXISTS `oql`.`travel`;
CREATE TABLE `oql`.`travel`
(
    `APPLY_ID`    INT          NOT NULL AUTO_INCREMENT,
    `USER_ID`     VARCHAR(32)  NOT NULL,
    `START_DATE`  DATE         NOT NULL,
    `END_DATE`    DATE         NOT NULL,
    `REASON`      VARCHAR(200) NOT NULL DEFAULT '',
    `ENTP_KEY`    VARCHAR(32)  NOT NULL,
    `CREATED_BY`  VARCHAR(20)  NOT NULL,
    `CREATED_AT`  DATETIME     NOT NULL,
    `MODIFIED_BY` VARCHAR(20) NULL,
    `MODIFIED_AT` DATETIME NULL,
    PRIMARY KEY (`APPLY_ID`)
) COMMENT = '出差申请表';
