package net.cf.form.engine.repository.data;

/**
 * 数据字段
 *
 * @author clouds
 */
@Deprecated
public class DataField implements IDataField {

    /**
     * 字段的名称
     */
    protected String name;

    /**
     * 字段的DB列名称
     */
    protected String columnName;

    /**
     * 字段的数据类型
     */
    protected DataType dataType;

    /**
     * 是否主键
     */
    protected boolean primary;

    /**
     * 是否自动生成主键
     */
    protected boolean autoGenerate;

    public DataField(String name, DataType dataType) {
        this.name = name;
        this.dataType = dataType;
    }

    public DataField(String name, String columnName, DataType dataType) {
        this.name = name;
        this.columnName = columnName;
        this.dataType = dataType;
    }

    @Override
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getColumnName() {
        return columnName != null ? columnName : name;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    public DataType getDataType() {
        return dataType;
    }

    public void setDataType(DataType dataType) {
        this.dataType = dataType;
    }

    /**
     * 返回字段是否主键
     *
     * @return
     */
    public boolean isPrimary() {
        return primary;
    }

    /**
     * 设置字段是否主键
     *
     * @param primary
     */
    public void setPrimary(boolean primary) {
        this.primary = primary;
    }

    /**
     * 返回字段是否自动生成的主键
     *
     * @return
     */
    public boolean isAutoGenerated() {
        return autoGenerate;
    }

    /**
     * 设置字段是否自动生成的主键
     *
     * @param autoGenerate
     */
    public void setAutoGenerate(boolean autoGenerate) {
        this.autoGenerate = autoGenerate;
        if (autoGenerate) {
            this.primary = true;
        }
    }
}

