package net.cf.object.engine.def.field;

import net.cf.object.engine.def.ObjectTestImpl;
import net.cf.object.engine.object.DataType;
import net.cf.object.engine.object.XField;

import java.util.List;
import java.util.Map;

public class FieldTestImpl implements XField {

    private final ObjectTestImpl owner;

    private final FieldDef fieldDef;

    public FieldTestImpl(ObjectTestImpl owner, FieldDef fieldDef) {
        this.owner = owner;
        this.fieldDef = fieldDef;
    }

    @Override
    public ObjectTestImpl getOwner() {
        return owner;
    }

    public FieldDef getFieldDef() {
        return fieldDef;
    }

    @Override
    public String getName() {
        return fieldDef.getName();
    }

    @Override
    public String getCode() {
        return fieldDef.getCode();
    }

    @Override
    public String getColumnName() {
        return fieldDef.getColumnName();
    }

    @Override
    public boolean isPrimary() {
        return XField.super.isPrimary();
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Override
    public boolean isCollection() {
        return fieldDef.isCollection();
    }

    @Override
    public DataType getDataType() {
        return fieldDef.getDataType();
    }

    @Override
    public Object getDefaultValue() {
        return this.fieldDef.getDefaultValue();
    }

    @Override
    public List<FieldPropertyTestImpl> getProperties() {
        return this.fieldDef.getProperties();
    }

    @Override
    public Map<String, Object> getAttributeValues() {
        return this.fieldDef.getAttrValueMap();
    }
}
