package net.cf.object.engine.def.field;

import net.cf.object.engine.def.ObjectTestImpl;
import net.cf.object.engine.object.DataType;
import net.cf.object.engine.object.XField;

import java.util.List;
import java.util.Map;

public class FieldTestImpl implements XField {

    private final ObjectTestImpl owner;

    private final FieldDef fieldDef;

    public FieldTestImpl(ObjectTestImpl owner, FieldDef fieldDef) {
        this.owner = owner;
        this.fieldDef = fieldDef;
    }

    @Override
    public ObjectTestImpl getOwner() {
        return owner;
    }

    public FieldDef getFieldDef() {
        return fieldDef;
    }

    @Override
    public String getCode() {
        return fieldDef.getName();
    }

    @Override
    public String getName() {
        return fieldDef.getCode();
    }

    @Override
    public String getColumnName() {
        return fieldDef.getName();
    }

    @Override
    public boolean isPrimary() {
        return XField.super.isPrimary();
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Override
    public boolean isCollection() {
        return fieldDef.isCollection();
    }

    @Override
    public DataType getDataType() {
        return fieldDef.getDataType();
    }

    @Override
    public Object getDefaultValue(Map<String, Object> dataMap) {
        DefaultValueConfig defaultValueConfig = this.fieldDef.getDefaultValueConfig();
        if (defaultValueConfig == null) {
            // 没有配置设置值，返回null
            return null;
        }

        // 根据默认值的类型时是常量和表达式来执行不同的逻辑
        DefaultValueType defaultValueType = defaultValueConfig.getType();
        if (DefaultValueType.LITERAL == defaultValueType) {
            return defaultValueConfig.getValue();
        } else if (DefaultValueType.FORMULA == defaultValueType) {
            return FormulaTestUtils.eval(defaultValueConfig.getValue(), dataMap);
        } else {
            return null;
        }
    }

    @Override
    public List<FieldPropertyTestImpl> getProperties() {
        return this.fieldDef.getProperties();
    }

    @Override
    public Map<String, Object> getAttrValues() {
        return this.fieldDef.getAttributeValueMap();
    }
}
